[tool.ruff]
line-length = 100
indent-width = 4
target-version = "py312"

[tool.ruff.lint]
select = ["E", "W", "N", "Q", "COM", "RSE", "RET"]
flake8-quotes.inline-quotes = "single"

[tool.ruff.format]
quote-style = "single"
